export class CanvasEditor{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.image=new Image();this.blurRegions=[];this.subtitleRect={x:.08,y:.78,w:.84,h:.16};this.tool="blur";this.selected=null;this.drag=null;canvas.addEventListener("pointerdown",e=>this.down(e));canvas.addEventListener("pointermove",e=>this.move(e));canvas.addEventListener("pointerup",e=>this.up(e))}
  async setImage(dataUrl){await new Promise((resolve,reject)=>{this.image.onload=resolve;this.image.onerror=reject;this.image.src=dataUrl});this.canvas.width=this.image.naturalWidth||1280;this.canvas.height=this.image.naturalHeight||720;this.draw()}
  setRegions(regions,subtitle){this.blurRegions=(regions||[]).map(r=>({...r}));if(subtitle)this.subtitleRect={...subtitle};this.selected=null;this.draw()}
  point(event){const r=this.canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))}}
  hit(p){const items=this.blurRegions.map((rect,index)=>({kind:"blur",index,rect}));items.push({kind:"subtitle",index:-1,rect:this.subtitleRect});return items.reverse().find(({rect})=>p.x>=rect.x&&p.x<=rect.x+rect.w&&p.y>=rect.y&&p.y<=rect.y+rect.h)}
  down(event){const p=this.point(event),hit=this.hit(p);if(hit&&hit.kind===this.tool){this.selected={kind:hit.kind,index:hit.index};this.drag={type:"move",start:p,original:{...hit.rect}}}else{this.drag={type:"create",start:p};this.selected=null}this.canvas.setPointerCapture(event.pointerId)}
  move(event){if(!this.drag)return;const p=this.point(event);if(this.drag.type==="move"){const target=this.selected.kind==="subtitle"?this.subtitleRect:this.blurRegions[this.selected.index];target.x=Math.max(0,Math.min(1-target.w,this.drag.original.x+p.x-this.drag.start.x));target.y=Math.max(0,Math.min(1-target.h,this.drag.original.y+p.y-this.drag.start.y))}else this.drag.current=p;this.draw()}
  up(event){if(!this.drag)return;const p=this.point(event);if(this.drag.type==="create"){const rect={x:Math.min(this.drag.start.x,p.x),y:Math.min(this.drag.start.y,p.y),w:Math.abs(p.x-this.drag.start.x),h:Math.abs(p.y-this.drag.start.y)};if(rect.w>.02&&rect.h>.02){if(this.tool==="subtitle"){this.subtitleRect=rect;this.selected={kind:"subtitle",index:-1}}else{this.blurRegions.push(rect);this.selected={kind:"blur",index:this.blurRegions.length-1}}}}this.drag=null;this.draw()}
  deleteSelected(){if(this.selected?.kind==="blur")this.blurRegions.splice(this.selected.index,1);this.selected=null;this.draw()}
  draw(){const{ctx,canvas}=this;ctx.clearRect(0,0,canvas.width,canvas.height);if(this.image.complete)ctx.drawImage(this.image,0,0,canvas.width,canvas.height);const box=(rect,color,label,selected)=>{const x=rect.x*canvas.width,y=rect.y*canvas.height,w=rect.w*canvas.width,h=rect.h*canvas.height;ctx.fillStyle=`${color}33`;ctx.fillRect(x,y,w,h);ctx.strokeStyle=color;ctx.lineWidth=selected?5:3;ctx.strokeRect(x,y,w,h);ctx.fillStyle=color;ctx.font=`bold ${Math.max(14,canvas.width/55)}px sans-serif`;ctx.fillText(label,x+6,y+22)};this.blurRegions.forEach((r,i)=>box(r,"#ff4f82",`BLUR ${i+1}`,this.selected?.kind==="blur"&&this.selected.index===i));box(this.subtitleRect,"#8ee52e","PHỤ ĐỀ VIỆT",this.selected?.kind==="subtitle");if(this.drag?.type==="create"&&this.drag.current){const a=this.drag.start,b=this.drag.current;box({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)},this.tool==="blur"?"#ff4f82":"#8ee52e","MỚI",false)}}
}
